
# version: 2

# models:
#   - name: analysis_yt_data
#     description: "test analysis"
#     columns:
#       - name: GENRE
#         description: "test genre"
#         tests:
#           - unique
#           - not_null

