dbt_demo:
  outputs:
    dev:
      account: ykzjwal-ar56104
      database: ANALYTICS
      password: Kaviandlilo94
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 10
      type: snowflake
      user: KavindiMudunkotuwa
      warehouse: COMPUTE_WH
  target: dev
dbt_project:
  outputs:
    dev:
      account: ykzjwal-ar56104
      database: ANALYTICS
      password: Kaviandlilo94
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 10
      type: snowflake
      user: KavindiMudunkotuwa
      warehouse: COMPUTE_WH
  target: dev
