demo_dbt:
  outputs:
    dev:
      account: jtrkojp-aq61018
      database: ANALYTICS
      password: koshitha@1234A
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 10
      type: snowflake
      user: KOSHITHA
      warehouse: TRANSFORMING

    prod:
      account: jtrkojp-aq61018
      database: ANALYTICS
      password: koshitha@1234A
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 10
      type: snowflake
      user: KOSHITHA
      warehouse: TRANSFORMING
    
  target: dev
